/*
    BUT pneumobil - Copyright (C) 2018 Jakub Kaderka.

    This file is part of BUT pneumobil ECU.

    BUT pneumobil is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    BUT pneumobil is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file    ecu/config_items.c
 * @brief   Configuration storage subsystem - configuration items
 *
 * Generated automatically by script, do not modify
 *
 * @addtogroup app-ecu
 * @{
 */

#include "config_items.h"

/** Default uint values - autogenerated by sw/generators/config_items.py */
const uint32_t config_default_uint[CONFIG_UINT_COUNT] = {
    0, /* CONFIG_UINT_PISTON_LEN */
    540, /* CONFIG_UINT_WHEEL_DIA_MM */
    60, /* CONFIG_UINT_PULSES_PER_WHEEL_ROTATION */
    10, /* CONFIG_UINT_SENDER_PERIOD_MS */
    30, /* CONFIG_UINT_FILLING_PCT_LONG_DIST */
    2000, /* CONFIG_UINT_DEADTIME_MS_LONG_DIST */
    95, /* CONFIG_UINT_FILLING_PCT_ARCADE */
    50, /* CONFIG_UINT_DEADTIME_MS_ARCADE */
    100, /* CONFIG_UINT_FILLING_PCT_ACCELERATION */
    0, /* CONFIG_UINT_DEADTIME_MS_ACCELERATION */
    0, /* CONFIG_UINT_DEFAULT_MODE */
};

/** Default bool values - autogenerated by sw/generators/config_items.py */
const uint8_t config_default_bool[CONFIG_BOOL_COUNT/8+1] = {
    0x00,
};

/** Default float values - autogenerated by sw/generators/config_items.py */
const float config_default_float[CONFIG_FLOAT_COUNT] = {
    0, /* DUMMY */
};

/** @} */
