/*
    BUT pneumobil - Copyright (C) 2018 Jakub Kaderka.

    This file is part of BUT pneumobil ECU.

    BUT pneumobil is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    BUT pneumobil is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file    ecu/config_items.h
 * @brief   Configuration storage subsystem - configuration items
 *
 * Generated automatically by script, do not modify
 *
 * @addtogroup app-ecu
 * @{
 */

#ifndef __ECU_CONFIG_ITEMS_H
#define __ECU_CONFIG_ITEMS_H

#include <types.h>

/** Config items list - autogenerated by sw/generators/config_items.py */
typedef enum {
    CONFIG_UINT_PISTON_LEN, /* Piston len in encoder steps */
    CONFIG_UINT_WHEEL_DIA_MM, /* Diameter of the wheel where the speed sensor is placed */
    CONFIG_UINT_PULSES_PER_WHEEL_ROTATION, /* Amount of holes in the shade on the back wheel for speed measurement (pulses generated in single rotation) */
    CONFIG_UINT_SENDER_PERIOD_MS, /* Send car state over can every x ms */
    CONFIG_UINT_FILLING_PCT_LONG_DIST, /* Filling percentage for long distance race */
    CONFIG_UINT_DEADTIME_MS_LONG_DIST, /* Deadtime for long distance race */
    CONFIG_UINT_FILLING_PCT_ARCADE, /* Filling percentage for arcade race */
    CONFIG_UINT_DEADTIME_MS_ARCADE, /* Deadtime for arcade race */
    CONFIG_UINT_FILLING_PCT_ACCELERATION, /* Acceleration filling percentage */
    CONFIG_UINT_DEADTIME_MS_ACCELERATION, /* Acceleration deadtime */
    CONFIG_UINT_DEFAULT_MODE, /* Default ecu mode after boot */
    CONFIG_UINT_COUNT,
} config_item_uint_t;

/** Config items list - autogenerated by sw/generators/config_items.py */
typedef enum {
    CONFIG_BOOL_ENCODER_INVERT, /* Invert direction of encoder counting */
    CONFIG_BOOL_PNEU_NON_BLOCK, /* Ignore checking pneu enabled */
    CONFIG_BOOL_ENDSTOP_INVERT, /* Invert endstop polarity (1 means active low) */
    CONFIG_BOOL_COUNT,
} config_item_bool_t;

/** Config items list - autogenerated by sw/generators/config_items.py */
typedef enum {
    CONFIG_FLOAT_DUMMY,
    CONFIG_FLOAT_COUNT,
} config_item_float_t;

extern const uint32_t config_default_uint[CONFIG_UINT_COUNT];

extern const uint8_t config_default_bool[CONFIG_BOOL_COUNT/8+1];

extern const float config_default_float[CONFIG_FLOAT_COUNT];

#endif

/** @} */
