/*
    BUT pneumobil - Copyright (C) 2018 Jakub Kaderka.

    This file is part of BUT pneumobil.

    BUT pneumobil is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    BUT pneumobil is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file    comm.h
 * @brief   Communication protocol
 *
 * @addtogroup modules-comm
 * @{
 */

#ifndef __MODULES_COMM_H
#define __MODULES_COMM_H

#include <types.h>
#include <version.h>

/** Maximum allowed payload length that can be received (up to 0xff) */
#define COMM_MAX_PAYLOAD_LEN 0xfe

/** Communication node ids, used for CAN addressing */
typedef enum {
    COMM_NODE_DEBUG = 0x00,
    COMM_NODE_PSU = 0x01,
    COMM_NODE_HMI = 0x02,
    COMM_NODE_ECU = 0x03,
    COMM_NODE_SDU = 0x04,
    COMM_NODE_UNKNOWN = 0x05,
    COMM_NODE_BROADCAST = 0x0f,    /* For transmission only */
} comm_node_t;

/** Communication priority, used by CAN for prioritizing messages */
typedef enum {
    COMM_PRIORITY_CRITICAL = 0x00,
    COMM_PRIORITY_NORMAL = 0x01,
    COMM_PRIORITY_LOG = 0x02,
    COMM_PRIORITY_DEBUG = 0x03
} comm_priority_t;

/** Error states during communication */
typedef enum {
    COMM_OK = 0x00,                     /** Communication was ok */
    /* errors sent in response */
    COMM_ERR_UNSUPPORTED_CMD = 0x01,    /** The command received is not implemented */
    COMM_ERR_INCORRECT_LEN = 0x02,      /** Length of the command params does not match expected value */
    COMM_ERR_INCORRECT_PARAM = 0x03,    /** Incorrect parameter value for given cmd */

    /* internal errors */
    COMM_ERR_TIMEOUT = 0x04,            /** Command timeouted */
    COMM_ERR_FORMAT = 0x05,             /** Received data format is bad */
    COMM_ERR_LINK = 0x06,               /** Failed on link layer - CRC, etc */
} comm_error_t;

/** Command IDs - autogenerated by sw/generators/comm_cmd.py */
typedef enum {
/* Generic commands*/
    COMM_CMD_SYSTEM_STATUS = 0x00,    /* Get device generic state */
    COMM_CMD_SET_LOG_MASK = 0x01,    /* Set logging mask */
    COMM_CMD_GET_LOG_MASK = 0x02,    /* Get logging mask */
    COMM_CMD_SET_CONFIG = 0x03,    /* Set configuration item */
    COMM_CMD_GET_CONFIG = 0x04,    /* Get config item value */
    COMM_CMD_RESET_CONFIG = 0x05,    /* Restart all config items to defaults */
    COMM_CMD_GET_ALL_CONFIG = 0x06,    /* Get all config items */
    COMM_CMD_LOG_MESSAGE = 0x07,    /* System log message */

/* Flash commands*/
    COMM_CMD_FLASH_VERSION = 0x10,    /* Current info about flash */
    COMM_CMD_GET_FLASH_VERSION = 0x11,    /* Get info about image stored */
    COMM_CMD_FLASH_MODE = 0x12,    /* Current flashing state */
    COMM_CMD_FLASH_INIT = 0x13,    /* Initialize flashing sequence */
    COMM_CMD_FLASH_DATA = 0x14,    /* Send data to be flashed */
    COMM_CMD_FLASH_FINISH = 0x15,    /* Finish flashing / cancel flash operation */
    COMM_CMD_REBOOT = 0x16,    /* Reboot the device */

/* ECU commands*/
    COMM_CMD_CAR_STATE = 0x20,    /* Current state of the car */
    COMM_CMD_CAR_IO = 0x21,    /* Inputs and outputs of the ecu */
    COMM_CMD_PNEU_STATE = 0x22,    /* Current state of the pneumatic circuit */
    COMM_CMD_GPS_POSITION = 0x23,    /* Car gps position */
    COMM_CMD_TEMPS = 0x24,    /* Temperatures in pneumatic circuit */
    COMM_CMD_START_RACE = 0x25,    /* Set pneumatic mode and start race */
    COMM_CMD_ECU_DEBUG = 0x26,    /* Debug mode IO control */
    COMM_CMD_ECU_USER_IO = 0x27,    /* Set user controllable outputs */
    COMM_CMD_SET_PNEU_PARAMS = 0x28,    /* Setup filling and turnaround time */
    COMM_CMD_GET_PNEU_PARAMS = 0x29,    /* Read filling and turnaround time */

/* PSU commands*/
    COMM_CMD_BATTERY_STATE = 0x30,    /* Current battery state */
    COMM_CMD_PSU_CURRENT = 0x31,    /* Currents to branches */
    COMM_CMD_PSU_VOLTAGE = 0x32,    /* Voltages of all branches */

/* HMI commands*/
} comm_cmd_id_t;

#ifdef BOARD_ECU
    #define COMM_MY_ID COMM_NODE_ECU
#elif defined BOARD_HMI
    #define COMM_MY_ID COMM_NODE_HMI
#elif defined BOARD_PSU
    #define COMM_MY_ID COMM_NODE_PSU
#elif defined BOARD_SDU
    #define COMM_MY_ID COMM_NODE_SDU
#else
    #error "BOARD_NAME must be defined"
#endif

#ifdef BOARD_HMI
    #include "state.h"
    #include "logger.h"
extern bool Comm_SendEcuStartRace(state_race_mode_t mode);
extern bool Comm_SendEcuDebug(state_valve_t front1, state_valve_t front2,
        state_valve_t back1, state_valve_t back2, bool horn, bool brake,
        bool out1, bool out2);
extern bool Comm_SendEcuUserIo(bool horn, bool brake, bool out1, bool out2);
extern bool Comm_SendPneuParams(state_race_mode_t mode, uint8_t filling_pct,
        uint16_t deadtime_ms);
extern bool Comm_ReadPneuParams(state_race_mode_t mode, uint8_t *filling_pct,
        uint16_t *deadtime_ms);
#endif

#ifdef BOARD_ECU
    #include "ecu_io.h"
    #include "ecu.h"
    #include "race.h"
extern void Comm_SendCarState(uint16_t speed_dms, uint16_t speed_avg_dms,
        uint16_t distance_m, race_mode_t race_mode);
extern void Comm_SendCarIO(const ecu_inputs_t *inputs,
        const ecu_valves_t *valves, uint8_t gear);
extern void Comm_SendPneuState(uint16_t press1_kpa, uint16_t press2_kpa,
        uint16_t press3_kpa, uint8_t piston_pct);
#endif

#ifdef BOARD_PSU
extern void Comm_SendBatteryState(uint16_t b1_mv, uint16_t b2_mv,
        uint16_t cur_ma, uint8_t charge_pct);
extern void Comm_SendPSUCurrent(uint16_t v5_ma, uint16_t v12_ma,
        uint16_t v24_ma);
extern void Comm_SendPSUVoltage(uint16_t v5_mv, uint16_t v12_mv,
        uint16_t v24_mv);
#endif

extern void Comm_SendSystemStatus(void);

/**
 * Initialize communication module and its submodules
 */
extern void Comm_Init(void);

#endif

/** @} */
