/*
    BUT pneumobil - Copyright (C) 2018 Jakub Kaderka.

    This file is part of BUT pneumobil ECU.

    BUT pneumobil is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    BUT pneumobil is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file    hmi/config_items.c
 * @brief   Configuration storage subsystem - configuration items
 *
 * Generated automatically by script, do not modify
 *
 * @addtogroup app-hmi
 * @{
 */

#include "config_items.h"

/** Default uint values - autogenerated by sw/generators/config_items.py */
const uint32_t config_default_uint[CONFIG_UINT_COUNT] = {
    0, /* CONFIG_UINT_TOUCH_CALIB */
};

/** Default bool values - autogenerated by sw/generators/config_items.py */
const uint8_t config_default_bool[CONFIG_BOOL_COUNT/8+1] = {
    0x00,
};

const float config_default_float[CONFIG_FLOAT_COUNT] = {
    0.0,
};

/** @} */
